# Usa la imagen de Python
FROM python:3.12

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de la aplicación
COPY . /app

# Instala las dependencias
RUN pip install flask requests

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la app
CMD ["python", "app.py"]
